


pipeline {
    agent any
    tools {
    	maven 'M3'
  	}
    stages {
        stage('build') {
            steps {
                //sh 'mvn --version'
                sh 'mvn -f arith-api/pom.xml compile'
            }
        }
    }
} 