


pipeline {
    agent any
    tools {
    	maven 'M3'
  	}
    stages {
    	stage('echo') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('build') {
            steps {
                sh 'mvn -f arith-api/pom.xml clean package'
            }
            post {
	            always {
	                junit 'arith-api/target/surefire-reports/*.xml'
	            }
         	}
        }
        
    	stage('Publish to Artifactory') {
	        steps {
	            script {
	                rtServer (
					    id: "Artifactory-1",
					    url: "http://13.234.38.34:8081//artifactory",
					    username: "user",
					    password: "password"
					)
	            }
	       }
    	}
    	
    	stage('Staging') {
	        steps {
	           input "Ready to go"
	       }
    	}
    	
    	stage('Deploy / Run') {
	        steps {
	           sh "java -jar arith-api/target/arith-api-0.0.1-SNAPSHOT.jar --port=8181 com.example.demo.ArithApiApplication
	       }
    	}
     
 	}
 	post {
	    always {
	         emailext subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                to: "Developer",
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}"
	    }
	}
} 