


pipeline {
    agent any
    tools {
    	maven 'M3'
  	}
    stages {
    	stage('echo') {
            steps {
                sh 'mvn --version'
            }
        }
        stages {
	        stage('build') {
	            steps {
	                sh 'mvn -f arith-api/pom.xml clean package'
	            }
	        }
	        post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
	         }
        }
        
    }
} 